repos:
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        name: black
        description: "applies black formatter to .py files"
        entry: black
        language: python
        types: [python]
  - repo: local
    hooks:
      - id: check-added-large-files
        name: Check for added large files
        entry: check-added-large-files
        language: system
      - id: check-toml
        name: Check Toml
        entry: check-toml
        language: system
        types: [toml]
      - id: check-yaml
        exclude: docs/
        name: Check Yaml
        entry: check-yaml
        language: system
        types: [yaml]
      - id: end-of-file-fixer
        exclude: docs/
        name: Fix End of Files
        entry: end-of-file-fixer
        language: system
        types: [text]
        stages: [commit, push, manual]
      - id: reorder-python-imports
        exclude: docs/
        name: Reorder python imports
        entry: reorder-python-imports
        language: system
        types: [python]
        args: [--application-directories=src]
      - id: trailing-whitespace
        exclude: docs/
        name: Trim Trailing Whitespace
        entry: trailing-whitespace-fixer
        language: system
        types: [text]
        stages: [commit, push, manual]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.0
    hooks:
      - id: prettier
        exclude: docs/
  - repo: https://github.com/kynan/nbstripout
    rev: 0.4.0
    hooks:
      - id: nbstripout
        name: nbstripout
        description: "nbstripout: strip output from Jupyter and IPython notebooks"
        entry: nbstripout
        language: python
        types: [jupyter]
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.0.3
    hooks:
      - id: detect-secrets
        name: detect-secrets - Detect secrets in staged code
        args:
          [
            "--baseline",
            ".secrets.baseline",
            "--exclude-files",
            '.*\.ipynb$|poetry.lock',
          ]
        exclude: .*/tests/.*|^\.cruft\.json$
      - id: detect-secrets
        name: "detect-secrets-jupyter"
        args:
          [
            "--exclude-files",
            ".*[^i][^p][^y][^n][^b]$",
            "--exclude-lines",
            '"(hash|id|image/\w+)":.*',
          ]
